# -*- coding: utf-8 -*-
"""Pandas_Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14o-58we5ct8XcDR5d993c-tk9RHwkiGd
"""

import numpy as np
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Practice/titanic.csv")

df

df_f=pd.read_csv('amazon_fires.csv', encoding='ISO-8859-10')
df_f

df.info()

df.describe()

df.columns

df.head()

df.tail()

df['sex'].unique()

df['sex'].value_counts()

df['ticket'].value_counts()

df.sort_values(by='fare').head()

df.sort_values(by='fare', ascending=False).head()

df1=df.sort_values(by='fare', ascending=False)
df1

df1.reset_index()

df1=df.sort_values(by='fare',ascending=False)
df1.reset_index(inplace=True)
df1

df1.drop('index',axis=1,inplace=True)
df1

df[1:5]

df[-1:-5]

df['name'][1:4]

df.loc[4,'name']

df.loc[0,['name','ticket']]

df.loc[[0,1],['name','ticket']]

df.loc[1::4,['name','ticket']]